# Generated by Django 3.2.18 on 2023-03-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('pages', '0022_auto_20230324_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('google_maps_address', models.URLField(blank=True, max_length=500)),
                ('messenger_link', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('seo_image', models.ForeignKey(blank=True, help_text='The image displayed when a page gets posted on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Seo Image')),
            ],
            options={
                'verbose_name': 'Service page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceFinderPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_title', models.CharField(blank=True, max_length=255)),
                ('header_subtitle', models.TextField(blank=True)),
                ('header_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Video file')),
                ('seo_image', models.ForeignKey(blank=True, help_text='The image displayed when a page gets posted on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Seo Image')),
            ],
            options={
                'verbose_name': 'Service finder page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
