# Generated by Django 3.2.18 on 2023-03-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_delete_staticpage'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefinderpage',
            name='header_video_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Poster'),
        ),
    ]
