# Generated by Django 3.2.18 on 2023-03-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20230327_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicelocation',
            options={'ordering': ['order'], 'verbose_name': 'Service Location', 'verbose_name_plural': 'Service Locations'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['order'], 'verbose_name': 'Service Type', 'verbose_name_plural': 'Service Types'},
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
