# Generated by Django 3.2.18 on 2023-03-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20230327_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicelocation', verbose_name='Service Location'),
        ),
    ]
