# Generated by Django 3.2.18 on 2023-04-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicepage_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='about',
            new_name='text',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='preview_text',
            field=models.TextField(blank=True, help_text='If populated the text will be displayed on the service finder page.If omitted the first 50 characters of the below text field will be displayed.'),
        ),
    ]
