# Generated by Django 3.2.18 on 2023-04-11 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_alter_homepage_header_image'),
        ('services', '0006_auto_20230406_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicefinderpage',
            name='header_video',
        ),
        migrations.AddField(
            model_name='servicefinderpage',
            name='header_youtube_video_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='servicefinderpage',
            name='header_video_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Header Video Poster'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='preview_text',
            field=models.TextField(blank=True, help_text='If populated the text will be displayed on the service finder page.If omitted the first 50 words of the below text field will be displayed.'),
        ),
    ]
