# Generated by Django 3.2.18 on 2023-06-16 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_alter_aboutpage_body'),
        ('services', '0008_auto_20230411_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefinderpage',
            name='header_video_poster',
            field=models.ForeignKey(blank=True, help_text='Recommended aspect ratio 16:9 and image dimensions 320x180', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Header youtube video poster'),
        ),
    ]
