# Generated by Django 3.2.18 on 2023-06-21 05:14

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicefinderpage_header_video_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
