# Generated by Django 3.2.18 on 2023-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicepageadditionalitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepageadditionalitem',
            name='content',
        ),
        migrations.AddField(
            model_name='servicepageadditionalitem',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
