# Generated by Django 3.2.18 on 2023-03-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
