# Generated by Django 3.2.18 on 2023-03-31 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230327_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_post',
            field=models.ForeignKey(blank=True, help_text='If populated the featured post will be displayed at Blog Index page and Blog Category Pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.postpage'),
        ),
    ]
