# Generated by Django 3.2.18 on 2023-04-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogindexpage_featured_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpage',
            old_name='intro',
            new_name='preview_text',
        ),
        migrations.RenameField(
            model_name='postpage',
            old_name='content',
            new_name='text',
        ),
    ]
