# Generated by Django 3.2.18 on 2023-04-11 09:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_auto_20230411_0928'),
        ('blog', '0010_postpage_seo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.fields.StreamField([('Social_Media_Posts_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('posts', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Recommended aspect ratio: 2/3 and image dimensions: 240x360', required=True)), ('youtube_video_id', wagtail.blocks.CharBlock(required=True))], required=False), required=False)), ('footnote', wagtail.blocks.CharBlock(required=False)), ('social_media_platforms', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True))], required=False), required=False)), ('show_section', wagtail.blocks.BooleanBlock(label='Show/Hide Section', required=False))]))], blank=True, use_json_field=False),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Recommended aspect ratio: 1/1 and image dimensions: 500x500', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Image'),
        ),
    ]
