# Generated by Django 3.2.18 on 2023-05-09 07:57

import datetime
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230411_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.fields.StreamField([('Social_Media_Posts_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('posts', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Recommended aspect ratio: 2/3 and image dimensions: 240x360', required=True)), ('youtube_video_id', wagtail.blocks.CharBlock(required=True))], required=False), required=False)), ('footnote', wagtail.blocks.CharBlock(required=False)), ('social_media_platforms', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True))], required=False), required=False)), ('show_section', wagtail.blocks.BooleanBlock(label='Show/Hide Section', required=False)), ('show_on_moya', wagtail.blocks.BooleanBlock(label='Show/Hide Section on Moya App', required=False))]))], blank=True, use_json_field=False),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime.today, help_text='If a future date is choosen then the post will not be shown to the end users until the date specified.', verbose_name='Published On'),
        ),
    ]
