# Generated by Django 3.2.18 on 2023-09-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogindexpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='show_posts_like_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='show_posts_social_media_share_links',
            field=models.BooleanField(default=True),
        ),
    ]
