# Generated by Django 3.2.18 on 2023-04-11 03:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('links', wagtail.fields.StreamField([('Internal', wagtail.blocks.PageChooserBlock()), ('External', wagtail.blocks.URLBlock())], blank=True, use_json_field=False)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Global Settings',
            },
        ),
    ]
