# Generated by Django 3.2.18 on 2023-04-11 03:53

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='background_image',
            field=wagtail.fields.StreamField([('Image', wagtail.images.blocks.ImageChooserBlock()), ('Document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=False),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='links',
            field=wagtail.fields.StreamField([('Page', wagtail.blocks.PageChooserBlock())], blank=True, use_json_field=False),
        ),
    ]
