# Generated by Django 3.2.18 on 2023-04-11 03:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_auto_20230411_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='links',
            field=wagtail.fields.StreamField([('Pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock()))], blank=True, use_json_field=False),
        ),
    ]
