# Generated by Django 3.2.18 on 2023-04-11 04:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_alter_globalsettings_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='links',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='sitemap',
            field=wagtail.fields.StreamField([('Links', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock()))], blank=True, use_json_field=False),
        ),
    ]
