# Generated by Django 3.2.18 on 2023-04-12 08:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_auto_20230411_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('script', models.TextField()),
                ('position', models.CharField(choices=[('head', 'Head'), ('body', 'Body')], default='head', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='helpers.globalsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
