# Generated by Django 3.2.18 on 2023-04-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0005_thirdpartyscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
    ]
