# Generated by Django 3.2.18 on 2023-05-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0006_auto_20230425_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyscript',
            name='hide_on_moya',
            field=models.BooleanField(default=False, help_text='Do not load Script on Moya App'),
        ),
    ]
