# Generated by Django 3.2.18 on 2023-06-16 03:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0007_thirdpartyscript_hide_on_moya'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='social_auth_allowed_emails',
            field=wagtail.fields.StreamField([('email_address', wagtail.blocks.EmailBlock())], blank=True, use_json_field=False),
        ),
    ]
