# Generated by Django 3.2.18 on 2023-09-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0008_globalsettings_social_auth_allowed_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
