# Generated by Django 3.2.18 on 2024-07-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0009_auto_20230901_0449.py'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='ga_measurement_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
