# Generated by Django 3.2.18 on 2023-03-24 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_privacypolicypage_termsandconditionspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='html_name',
            field=models.CharField(choices=[('404.html', '404.html'), ('500.html', '500.html'), ('blog/blog_category_page.html', 'blog/blog_category_page.html'), ('blog/blog_index_page.html', 'blog/blog_index_page.html'), ('blog/blog_page.html', 'blog/blog_page.html'), ('blog/post_page.html', 'blog/post_page.html'), ('includes/footer.html', 'includes/footer.html'), ('includes/main-nav.html', 'includes/main-nav.html'), ('pages/about_page.html', 'pages/about_page.html'), ('pages/home_page.html', 'pages/home_page.html'), ('pages/privacy_policy_page.html', 'pages/privacy_policy_page.html'), ('pages/service-finder.html', 'pages/service-finder.html'), ('pages/service.html', 'pages/service.html'), ('pages/static_page.html', 'pages/static_page.html'), ('pages/terms_and_conditions_page.html', 'pages/terms_and_conditions_page.html'), ('pages/text-page.html', 'pages/text-page.html'), ('seo.html', 'seo.html')], max_length=250, verbose_name='Choose html'),
        ),
    ]
