# Generated by Django 3.2.18 on 2023-03-24 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230324_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='seo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Seo Image'),
        ),
    ]
