# Generated by Django 3.2.18 on 2023-03-24 05:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_aboutpage_seo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='content',
            field=wagtail.fields.StreamField([('Time_Line_Section', wagtail.blocks.StructBlock([]))], blank=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='seo_image',
            field=models.ForeignKey(blank=True, help_text='The image displayed when a page gets posted on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Seo Image'),
        ),
    ]
