# Generated by Django 3.2.18 on 2023-03-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_aboutpage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='content',
            new_name='body',
        ),
    ]
