# Generated by Django 3.2.18 on 2023-03-24 06:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_aboutpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('Time_Line_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('year', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock())], required=False), required=False))])), ('Key_Figures_And_Testimonials_Section', wagtail.blocks.StructBlock([])), ('Faq_Section', wagtail.blocks.StructBlock([]))], blank=True, use_json_field=None),
        ),
    ]
