# Generated by Django 3.2.18 on 2023-03-24 06:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_aboutpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('Time_Line_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('year', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock())], required=False), required=False))])), ('Key_Figures_And_Testimonials_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('key_figures', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('numbers', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.CharBlock(required=False))], required=False), required=False)), ('testimonials', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('testimonial_giver_name', wagtail.blocks.CharBlock(required=False)), ('testimonial_giver_photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('testimonial', wagtail.blocks.TextBlock())], required=False), required=False))])), ('Faq_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=True)), ('answer', wagtail.blocks.TextBlock(required=True))], required=False), required=False))]))], blank=True, use_json_field=None),
        ),
    ]
