# Generated by Django 3.2.18 on 2023-03-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20230324_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='facebook_link',
            new_name='messenger_link',
        ),
    ]
