# Generated by Django 3.2.18 on 2023-03-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('pages', '0022_auto_20230324_0904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticPage',
        ),
    ]
