# Generated by Django 3.2.18 on 2023-03-27 04:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditionspage',
            name='body',
            field=wagtail.fields.StreamField([('Paragraph', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('width', wagtail.blocks.ChoiceBlock(choices=[('col-span-12', '100%'), ('col-span-7', '60%'), ('col-span-6', '50%'), ('col-span-5', '40%')], icon='cup'))]))], blank=True, use_json_field=False),
        ),
    ]
