# Generated by Django 3.2.18 on 2023-04-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_alter_homepage_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='messenger_link_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='moya_link_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_link_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
