# Generated by Django 3.2.18 on 2023-04-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_auto_20230411_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='messenger_link_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='moya_link_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='whatsapp_link_text',
            field=models.TextField(blank=True),
        ),
    ]
