# Generated by Django 3.2.18 on 2023-04-11 09:28

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_auto_20230411_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('Columns_Section', wagtail.blocks.StructBlock([('columns', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.StructBlock([('rich_text', wagtail.blocks.RichTextBlock())], required=False)), ('faq', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=True)), ('answer', wagtail.blocks.TextBlock(required=True))], required=False), required=False))], required=False)), ('button', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock()), ('button_link', wagtail.blocks.URLBlock(required=False)), ('show_for', wagtail.blocks.ChoiceBlock(choices=[('desktop_mobile', 'Desktop/Mobile'), ('desktop', 'Desktop'), ('mobile', 'Mobile')], icon='cup'))], required=False)), ('grid', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Recommended aspect ratio: 1/1 and image dimensions: 250x250')), ('text', wagtail.blocks.TextBlock())])))], required=False))])), ('width', wagtail.blocks.ChoiceBlock(choices=[('col-span-12', '100%'), ('col-span-7', '60%'), ('col-span-6', '50%'), ('col-span-5', '40%')], icon='cup'))]))), ('show_section', wagtail.blocks.BooleanBlock(label='Show/Hide Section', required=False))]))], blank=True, use_json_field=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('Featured_Blog_Post_Section', wagtail.blocks.StructBlock([('featured_blog_post', wagtail.blocks.PageChooserBlock(help_text='If empty the latest blog post will be displayed.', page_type=['blog.PostPage'], required=False)), ('show_section', wagtail.blocks.BooleanBlock(label='Show/Hide Section', required=False))])), ('Columns_Section', wagtail.blocks.StructBlock([('columns', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.StructBlock([('rich_text', wagtail.blocks.RichTextBlock())], required=False)), ('faq', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=True)), ('answer', wagtail.blocks.TextBlock(required=True))], required=False), required=False))], required=False)), ('button', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock()), ('button_link', wagtail.blocks.URLBlock(required=False)), ('show_for', wagtail.blocks.ChoiceBlock(choices=[('desktop_mobile', 'Desktop/Mobile'), ('desktop', 'Desktop'), ('mobile', 'Mobile')], icon='cup'))], required=False)), ('grid', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Recommended aspect ratio: 1/1 and image dimensions: 250x250')), ('text', wagtail.blocks.TextBlock())])))], required=False))])), ('width', wagtail.blocks.ChoiceBlock(choices=[('col-span-12', '100%'), ('col-span-7', '60%'), ('col-span-6', '50%'), ('col-span-5', '40%')], icon='cup'))]))), ('show_section', wagtail.blocks.BooleanBlock(label='Show/Hide Section', required=False))])), ('Social_Media_Posts_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('posts', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Recommended aspect ratio: 2/3 and image dimensions: 600x900', required=True)), ('link', wagtail.blocks.URLBlock(required=True))], required=False), required=False)), ('footnote', wagtail.blocks.CharBlock(required=False)), ('social_media_platforms', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True))], required=False), required=False)), ('show_section', wagtail.blocks.BooleanBlock(label='Show/Hide Section', required=False))])), ('Latest_Blog_Posts_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('number_of_posts_to_show', wagtail.blocks.IntegerBlock(default=4)), ('show_section', wagtail.blocks.BooleanBlock(label='Show/Hide Section', required=False))]))], blank=True, use_json_field=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_background_image',
            field=wagtail.fields.StreamField([('Image', wagtail.images.blocks.ImageChooserBlock(help_text='Recommended aspect ratio: 16/9 and image dimensions: 1920x1080')), ('Document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_image',
            field=wagtail.fields.StreamField([('Image', wagtail.images.blocks.ImageChooserBlock(help_text='Recommended aspect ratio: 1/1 and image dimensions: 525x525')), ('Document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=False),
        ),
    ]
