# Generated by Django 3.2.18 on 2023-04-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_auto_20230411_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Recommended aspect ratio: 7/6 and image dimensions: 630x540', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Header image'),
        ),
    ]
