# Generated by Django 3.2.18 on 2023-06-16 03:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_auto_20230509_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('Time_Line_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('year', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock())], required=False), required=False)), ('hide_section', wagtail.blocks.BooleanBlock(label='Hide Section', required=False)), ('hide_on_moya', wagtail.blocks.BooleanBlock(label='Hide Section on Moya App', required=False))])), ('Key_Figures_And_Testimonials_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('key_figures', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('numbers', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.CharBlock(required=False))], required=False), required=False)), ('testimonials', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(help_text='Recommended aspect ratio: 1:1 and image dimensions: 100x100', required=False)), ('description', wagtail.blocks.TextBlock())], required=False), required=False)), ('hide_section', wagtail.blocks.BooleanBlock(label='Hide Section', required=False)), ('hide_on_moya', wagtail.blocks.BooleanBlock(label='Hide Section on Moya App', required=False))])), ('Faq_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=True)), ('answer', wagtail.blocks.TextBlock(required=True))], required=False), required=False)), ('hide_section', wagtail.blocks.BooleanBlock(label='Hide Section', required=False)), ('hide_on_moya', wagtail.blocks.BooleanBlock(label='Hide Section on Moya App', required=False))]))], blank=True, use_json_field=False),
        ),
    ]
