# Generated by Django 3.2.18 on 2023-06-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_alter_aboutpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='messenger_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='moya_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
