# Generated by Django 3.2.18 on 2023-09-01 05:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_aboutpage_header_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='header_background_image',
            field=models.ForeignKey(blank=True, help_text='Recommended aspect ratio: 16/9 and image dimensions: 1920x1080', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Header background image'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Recommended aspect ratio: 7/6 and image dimensions: 630x540', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.customimage', verbose_name='Header image'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='header_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='header_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
