# Generated by Django 3.2.18 on 2023-09-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0062_homepage_header_background_color_hex_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='header_background_color_hex_code',
            field=models.CharField(blank=True, help_text='E.g #000000', max_length=255),
        ),
    ]
